# Generated by Django 4.1 on 2023-11-07 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planer_app', '0002_week_alter_task_frequency_tasksinweek_purchase_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='locator_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debt',
            name='purchase_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planer_app.purchase'),
        ),
        migrations.AlterField(
            model_name='tasksinweek',
            name='locator_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasksinweek',
            name='task_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planer_app.task'),
        ),
    ]
