# Generated by Django 4.1 on 2023-12-13 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("planer_app", "0003_alter_debt_locator_id_alter_debt_purchase_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasksinweek",
            name="locator_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
