# Generated by Django 4.1 on 2023-12-13 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("planer_app", "0004_alter_tasksinweek_locator_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasksinweek",
            name="task_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="planer_app.task"
            ),
        ),
    ]
