# Generated by Django 5.0 on 2025-10-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planer_app", "0008_alter_debt_purchase_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="debt",
            name="owed_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
    ]
