# Generated by Django 5.2.7 on 2025-10-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planer_app", "0010_galleryphoto_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryphoto",
            name="category",
            field=models.CharField(
                choices=[
                    ("events", "Events & Celebrations"),
                    ("food", "Food & Cooking"),
                    ("home", "Home & Improvements"),
                    ("pets", "Pets & Animals"),
                    ("travel", "Travel & Adventures"),
                    ("people", "People & Portraits"),
                    ("nature", "Nature & Outdoors"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
